select * from questions;
delete from questions;

insert into questions(id,question,q_type) values(1,'Why should you bundle database updates in your dialog programs?','mcsa');
 insert into questions(id,question,q_type) values(2,'Which steps are needed when implementing the singleton concept for class installation with minimum coding?' ,'mcma');
 insert into questions(id,question,q_type) values(3,'SAP ERP System contains a lock mechanism, fully independent of database locks, that allows you to set a lock that spans several dialog steps. These locks are known as SAP locks. Which of the following are functionalists of SAP Locks?' ,'mcma');
 insert into questions(id,question,q_type) values(4,'What will happen at run time when accessing a buffered table?' ,'mcma');
 insert into questions(id,question,q_type) values(5,'In a customer application, it is necessary to save texts with undefined size. Which table type do you use to minimize programming efforts?' ,'mcma');
 insert into questions(id,question,q_type) values(6,' Your transport request is released in system X and imported in system Y.Which method is used to transport the data from X to Y?' ,'mcma');
 insert into questions(id,question,q_type) values(7,'You perform an update task using update function modules and detect an error in the program that calls the update function modules. Which statement can be used to discard all update requests for the current SAP LUW?' ,'mcma');
 insert into questions(id,question,q_type) values(8,'Some ABAP programs can be run by a user by entering the program name or a transaction code. These programs are of type?' ,'mcma');
 insert into questions(id,question,q_type) values(9,'Which of the following enhancement options does not require any preparation from SAP?' ,'mcma');
 insert into questions(id,question,q_type) values(10,'How can you realize a modification free installation of objects in a customer-specific ABAP OO development?' ,'mcma');
 insert into questions(id,question,q_type) values(11,'What do you need to consider when using dynamic breakpoints?' ,'mcma');
 insert into questions(id,question,q_type) values(12,'Which task do you need to do after printing an Adobe form to avoid a program error?' ,'mcma');
 insert into questions(id,question,q_type) values(13,'Where do you place the language key field in a customer-specific text table to enable generic buffering of this table?' ,'mcma');
 insert into questions(id,question,q_type) values(14,'You cannot book the business data during processing of an incoming IDoc. How must the function module react to this problem?' ,'mcma');
 insert into questions(id,question,q_type) values(15,'How do you characterize customer and user exits?' ,'mcma');
 insert into questions(id,question,q_type) values(16,'In a customer program, a LOOP statement is processing time consuming database operations on transaction data. The execution of this program takes too long. How can you optimize the performance of this program?' ,'mcma');
 insert into questions(id,question,q_type) values(17,'What are the effects of a COMMIT WORK during program execution?' ,'mcma');
 insert into questions(id,question,q_type) values(18,'Business Objects encapsulate business data and functionality.' ,'mcma');
 insert into questions(id,question,q_type) values(19,'What kind of component of a business object are BAPIs ?Choose the correct answer\(s\).' ,'mcma');
 insert into questions(id,question,q_type) values(20,'3 Several BAPIs can participate in a single unit of work.' ,'mcma');
 insert into questions(id,question,q_type) values(21,'Operations that change the database must be carried out through' ,'mcma');
 insert into questions(id,question,q_type) values(22,'what is the name of the export parameter used to send messages back to the calling program?' ,'mcma');
 insert into questions(id,question,q_type) values(23,'Within the source code of a BAPI, you can execute a CALL TRANSACTION statement' ,'mcma');
 insert into questions(id,question,q_type) values(24,'Every currency amount field used in a BAPI must have a currency code field assigned to it.' ,'mcma');
 insert into questions(id,question,q_type) values(25,'Extension parameters enable application programmers to use preprogrammed user exits to enhance BAPI interfaces without modifications.' ,'mcma');
 insert into questions(id,question,q_type) values(26,'Which of the following statements is NOT true about a BAPI?' ,'mcma');
 insert into questions(id,question,q_type) values(27,'In which phase would you use a project form from the BAPI Explorer?' ,'mcma');
 insert into questions(id,question,q_type) values(28,'What process is used to establish the automatic transport of data between the view controller s context-attributes and the UI element in its layout?' ,'mcma');
 insert into questions(id,question,q_type) values(29,'What is the purpose of implicit enhancement points?' ,'mcma');
 insert into questions(id,question,q_type) values(30,'Why should you bundle database updates in your dialog programs?  ' ,'mcma');
 insert into questions(id,question,q_type) values(31,'hat happens when an authorization check fails?' ,'mcma');
 insert into questions(id,question,q_type) values(32,'Which of the following interface technologies are available in SAP systems?  ' ,'mcma');
 insert into questions(id,question,q_type) values(33,'You perform an update task using update function modules and detect an error in the program that calls the update function modules. Which statement can be used to discard all update requests for the current SAP LUW?' ,'mcma');
 insert into questions(id,question,q_type) values(34,'In addition to the primary key of an internal table, how many secondary indexes can you define for an internal table?' ,'mcma');
 insert into questions(id,question,q_type) values(35,'You have implemented a class CL_CUSTOMER in which you defined a private attribute. From where can you access this attribute directly?' ,'mcma');
 insert into questions(id,question,q_type) values(36,'Which of the following enhancement options does not require any preparation from SAP?  ' ,'mcma');
 insert into questions(id,question,q_type) values(37,'In which modularization units can you use parameters?' ,'mcma');
 insert into questions(id,question,q_type) values(38,'Which of the following ABAP standard types are numeric?  ' ,'mcma');
 insert into questions(id,question,q_type) values(39,'When should you use a hashed internal table?' ,'mcma');
 insert into questions(id,question,q_type) values(40,'You want to check the user input in the field FIELD_NAME on a classical screen. If an incorrect value is entered, the user should be able to correct the field value. How do you call the module CHECK_MODULE in the PAI of the screen to accomplish this?' ,'mcma');
 insert into questions(id,question,q_type) values(41,'Which of the following predefined ABAP types is incomplete?' ,'mcma');
 insert into questions(id,question,q_type) values(42,'Which prerequisites must be fulfilled before a repository object can be transported?' ,'mcma');
 insert into questions(id,question,q_type) values(43,'Which boundary conditions lead to improved access time to an internal table?' ,'mcma');
 insert into questions(id,question,q_type) values(44,'Which steps are needed when implementing the singleton concept for class instantiation with minimum coding?' ,'mcma');
 insert into questions(id,question,q_type) values(45,'Which of the following tasks does the BADI implementing class perform?' ,'mcma');
 insert into questions(id,question,q_type) values(46,'What will happen at runtime when accessing a buffered table?  ' ,'mcma');
 insert into questions(id,question,q_type) values(47,'Full Buffering would be appropriate for  ' ,'mcma');
 insert into questions(id,question,q_type) values(48,'What is the basic object of data Dictionary ' ,'mcma');
 insert into questions(id,question,q_type) values(49,'Search help can not be attach to: ' ,'mcma');
 insert into questions(id,question,q_type) values(50,'Sub query usually more efficient because:  ' ,'mcma');
 insert into questions(id,question,q_type) values(51,'It is better to buffer a table when ' ,'mcma');
 insert into questions(id,question,q_type) values(52,'In Inner and outter join ' ,'mcma');
 insert into questions(id,question,q_type) values(53,'What is invalid attribute of a domain ' ,'mcma');
 insert into questions(id,question,q_type) values(54,'Data element is an example of' ,'tf');
 insert into questions(id,question,q_type) values(55,'What is true ' ,'mcma');
 insert into questions(id,question,q_type) values(56,'Command flushes the database buffers ' ,'mcma');
 insert into questions(id,question,q_type) values(57,'How many lists can exist in parallel in an interactive reporting? ' ,'mcma');
 insert into questions(id,question,q_type) values(58,'What are the check tables and value tables? \(Multiple Answer\) ' ,'mcma');
 insert into questions(id,question,q_type) values(59,'What are presentation and application servers in SAP? \(Multiple Answer\) ' ,'mcma');
 insert into questions(id,question,q_type) values(60,'What is the difference between Synchronous and Asynchronous updates? \(Multiple Answer\) ' ,'mcma');
 insert into questions(id,question,q_type) values(61,'What are the main events an interactive report have? \(Multiple Answer\) ' ,'mcma');
 insert into questions(id,question,q_type) values(62,'How many types of tables exist in data dictionary? \(Multiple Answer\) ' ,'mcma');
 insert into questions(id,question,q_type) values(63,'What is the difference between UPLOAD and WS_UPLOAD? \(Multiple Answer\) ' ,'mcma');
 insert into questions(id,question,q_type) values(64,'Is Session Method, Asynchronous or Synchronous? ' ,'mcma');
 insert into questions(id,question,q_type) values(65,'What are the differences between SAP memory and ABAP memory? \(Multiple Answer\) ' ,'mcma');
 insert into questions(id,question,q_type) values(66,'Which data type cannot be used to define parameters. ' ,'mcma');